Repository buildpacks/rfcs, pull requests merged in 2020-10, with the labels that each got.

#106 RFC: Sub Team Maintainer (formerly author) Creates Repo Issues
  text/0000-create-repo-issues.md
Labels: Final Comment Period

#109 RFC: Relax Mixin Contract
  text/0000-relax-mixin-contract.md
Labels: Final Comment Period, issues-created/core, issues-created/implementation, issues-created/learning, issues-created/platform, spec/platform

#113 Distribution Team
  text/0000-distribution-team.md
Labels: Final Comment Period, issues-created/core, issues-created/implementation, issues-created/learning, issues-created/platform

#114 RFC: Build/Run image configs MUST contain env.PATH
  text/0000-stack-images-config-env-path-must-exist.md
Labels: Final Comment Period, issues-created/core, issues-created/implementation, issues-created/learning, issues-created/platform
