Repository buildpacks/rfcs, pull requests merged in 2021-06, with the labels that each got.

#153 Define a minimum standard for docs in order to ship the lifecycle
  text/0000-minimum-docs-lifecycle.md
Labels: Final Comment Period, Implementation, audience/cnb-contributors, sub-team-rfc

#159 Buildpack Authors Tooling Sub-Team
  text/0000-buildpack-authors-tooling-subteam.md
Labels: Core, Final Comment Period, audience/buildpack-author

#161 Intro video script
  text/0000-intro-video-script.md
Labels: Final Comment Period, Learning, sub-team-rfc
