Repository buildpacks/rfcs, pull requests merged in 2021-01, with the labels that each got.

#125 RFC for buildpack registry search api
  text/0000-buildpack-registry-search-api.md
Labels: Distribution, Final Comment Period, issues-created/distribution

#111 Stack buildpacks
  text/0000-stack-buildpacks.md
Labels: Final Comment Period, Implementation, issues-created/core, issues-created/implementation, issues-created/learning, issues-created/platform, spec/buildpack, spec/platform

#127 Added New Buildpack Descriptor Keys RFC
  text/0000-new-buildpack-toml-keys.md
Labels: Core, Final Comment Period, issues-created/learning, issues-created/platform, spec/buildpack

#126 Add RFC: CNB User Research 2021
  text/0000-CNB-user-research-2021.md
Labels: Core, Final Comment Period

#134 Add image working directory RFC
  text/0000-image-workdir.md
Labels: Final Comment Period, Implementation, issues-created/core, issues-created/distribution, issues-created/implementation, issues-created/learning, issues-created/platform
