Repository buildpacks/rfcs, pull requests merged in 2021-02, with the labels that each got.

#132 Move layer types to new table in layer.toml
  text/0000-layer-table.md
Labels: Final Comment Period, Implementation, issues-created/core, issues-created/distribution, issues-created/implementation, issues-created/learning, issues-created/platform

#135 Move analyze phase before detect
  text/0000-move-analyze-phase.md
Labels: Final Comment Period, Implementation, issues-created/core, issues-created/distribution, issues-created/implementation, issues-created/learning, issues-created/platform, spec/platform

#133 Windows build images use SIDs for User/Group ownership
  text/0000-windows-security-identifiers.md
Labels: Final Comment Period, Implementation, issues-created/core, issues-created/implementation, issues-created/learning, issues-created/platform, spec/platform

#136 Pack Command to Create a Buildpack Repo
  text/0000-pack-buildpack-create.md
Labels: Final Comment Period, Platform, issues-created/core, issues-created/implementation, issues-created/platform
