Repository buildpacks/rfcs, pull requests merged in 2022-11, with the labels that each got.

#234 Component maintainer role
  text/0000-governance-component-maintainer-role.md
Labels: audience/cnb-contributors, scope/project, team/bat, type/rfc, status/voting

#230 Allow setting environment variables using the build image
  text/0000-build-config.md
Labels: audience/buildpack-author, scope/project, team/bat, type/rfc, status/voting

#223 Additional OCI Artifacts
  text/0000-additonal-oci-artifacts.md
Labels: team/implementation, scope/project, type/rfc, status/steward-assigned
